Vagrant.configure("2") do |config|
  config.vm.define "docker-host"

  config.vm.box = "ubuntu/trusty64"

  config.vm.provider :virtualbox do |v|
    v.name    = "docker-host"
    v.memory  = 2048
    v.cpus    = 2
  end

  config.vm.provision "docker"

  # The following line terminates all ssh connections. Therefore Vagrant will
  # be forced to reconnect. That's a workaround to have the docker command in
  # the PATH.
  config.vm.provision "shell",
    inline: "ps aux | grep 'sshd:' | awk '{print $2}' | xargs kill"

  config.vm.network "private_network", ip: "192.168.50.4"

  config.vm.network "forwarded_port", guest: 3000, host: 3000
end
